# main text of home
name: Wushi Dong
bio: Applied Scientist at Amazon Web Services (AWS) | Deep learning & High-Performance Computing | Physics Ph.D. from U Chicago

# twitter summary info
description: This personal website is still under construction ...

# if it's an external image, update below for true
# better with square images
external-image: false
picture: ./assets/images/profile.jpeg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
  #resume-url: assets/resume.pdf

url: https://wushidonguc.github.io
permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

## if you don't want comments in your posts, leave categories empty
#disqus:
#  shortname: mydisqus # enter this from your disqus account
#  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: dongws
# youtube: myyoutube
# spotify: myspotify
github: wushidonguc
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
#medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: dongws@me.com

authors:
    wushidong:
        name: Wushi Dong
        bio: Applied Scientist at Amazon Web Services (AWS) | Deep Learning & High-Performance Computing | Physics PhD from U Chicago
        external-image: false
        picture: ./assets/images/profile.jpeg
        linkedin: dongws
        github: wushidonguc

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need "about" or , comment them out below
about: true

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need contacts, comment the *contacts* configs below
contact: true

# if you don't need "blog", comment the *blog* configs below
blog: false

# do you want to show the "date" of the posts?
show-date: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: false

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://wushidonguc.github.io
